#import "../fragments/GitHubTokenFragment.gql"

query AllGitHubTokensWithOrgAccess {
  allGitHubTokens(filters: { scopeIlike: "%read:org%" }) {
    totalCount
    edges {
      node {
        ...GitHubTokenFragment
      }
    }
  }
}
