#import "../fragments/ProductTypeFragment.gql"

query AllProductTypes {
  allProductTypes(sort: ORDER_ASC) {
    totalCount
    edges {
      node {
        ...productTypeFragment
        products {
          totalCount
        }
      }
    }
  }
}
