query QueryForSearchWindow {
  allProducts(sort: TIME_POSTED_DESC) {
    edges {
      node {
        id
        name
        type_ {
          id
          name
          singular
        }
      }
    }
  }
}
