fragment productTypeFragment on ProductType {
  id
  typeId
  name
  order
  indefArticle
  singular
  plural
  icon
  fields {
    edges {
      node {
        typeId
        fieldId
        field {
          fieldId
          name
          type_
        }
      }
    }
  }
}
