query AllGitHubOrgs {
  allGitHubOrgs {
    totalCount
    edges {
      node {
        login
        avatarUrl
        url
        memberships {
          totalCount
          edges {
            node {
              member {
                login
              }
            }
          }
        }
      }
    }
  }
}
