query AllGitHubUsers($orgMember: Boolean = false) {
  allGitHubUsers(filters: { orgMember: $orgMember }) {
    totalCount
    edges {
      node {
        login
        name
        avatarUrl
      }
    }
  }
}
