#import "./ProductTypeFragment.gql"

fragment productFragment on Product {
  id
  productId
  typeId
  type_ {
    ...productTypeFragment
  }
  name
  timePosted
  postingGitHubUser {
    id
    login
  }
  timeUpdated
  updatingGitHubUser {
    id
    login
  }
  paths {
    edges {
      node {
        id
        pathId
        path
        note
      }
    }
  }
  relations {
    edges {
      node {
        id
        relationId
        typeId
        type_ {
          id
          typeId
          name
          indefArticle
          singular
          plural
        }
        otherProductId
        other {
          id
          productId
          typeId
          type_ {
            ...productTypeFragment
          }
          name
        }
        reverseRelationId
        reverse {
          id
          relationId
          typeId
          type_ {
            id
            typeId
            name
          }
        }
      }
    }
  }
  note
  attributesUnicodeText {
    edges {
      node {
        id
        fieldId
        field {
          id
          name
          type_
        }
        value
      }
    }
  }
  attributesBoolean {
    edges {
      node {
        id
        fieldId
        field {
          id
          name
          type_
        }
        value
      }
    }
  }
  attributesInteger {
    edges {
      node {
        id
        fieldId
        field {
          id
          name
          type_
        }
        value
      }
    }
  }
  attributesFloat {
    edges {
      node {
        id
        fieldId
        field {
          id
          name
          type_
        }
        value
      }
    }
  }
  attributesDate {
    edges {
      node {
        id
        fieldId
        field {
          id
          name
          type_
        }
        value
      }
    }
  }
  attributesDateTime {
    edges {
      node {
        id
        fieldId
        field {
          id
          name
          type_
        }
        value
      }
    }
  }
  attributesTime {
    edges {
      node {
        id
        fieldId
        field {
          id
          name
          type_
        }
        value
      }
    }
  }
}
