#import "./ProductTypeFragment.gql"

fragment productFragment on Product {
  id
  productId
  typeId
  type_ {
    ...productTypeFragment
  }
  name
  contact
  dateProduced
  producedBy
  datePosted
  postedBy
  dateUpdated
  updatedBy
  paths {
    edges {
      node {
        id
        pathId
        path
        note
      }
    }
  }
  relations {
    edges {
      node {
        id
        relationId
        typeId
        type_ {
          id
          typeId
          name
          indefArticle
          singular
          plural
        }
        otherProductId
        other {
          id
          productId
          typeId
          type_ {
            ...productTypeFragment
          }
          name
        }
        reverseRelationId
        reverse {
          id
          relationId
          typeId
          type_ {
            id
            typeId
            name
          }
        }
      }
    }
  }
  note
}
