query QueryForProductAddFormRelationsPreview(
  $productRelationTypeId: Int!
  $productId: Int!
) {
  productRelationType(typeId: $productRelationTypeId) {
    id
    typeId
    singular
  }
  product(productId: $productId) {
    id
    productId
    name
    type_ {
      id
      typeId
      singular
    }
  }
}
