query QueryForFormRelations {
  allProductRelationTypes {
    edges {
      node {
        id
        typeId
        singular
        plural
      }
    }
  }
  allProducts(sort: NAME_ASC) {
    edges {
      node {
        productId
        name
        type_ {
          typeId
          singular
        }
      }
    }
  }
}
