query QueryForFormRelations {
  allProductRelationTypes {
    edges {
      node {
        id
        typeId
        indefArticle
        singular
        plural
        reverse {
          id
          typeId
          indefArticle
          singular
        }
      }
    }
  }
  allProducts(sort: NAME_ASC) {
    edges {
      node {
        productId
        name
        type_ {
          typeId
          singular
        }
      }
    }
  }
}
