query AllMaps {
  allMaps(sort: DATE_POSTED_DESC) {
    edges {
      node {
        id
        name
        datePosted
        mapper
        note
        mapFilePaths {
          edges {
            node {
              path
              note
            }
          }
        }
        beams {
          edges {
            node {
              name
            }
          }
        }
      }
    }
  }
}
