#import "./ProductFragment.gql"

query allProductsByTypeId($typeId: Int) {
  allProducts(filters: { typeId: $typeId }, sort: DATE_POSTED_DESC) {
    edges {
      node {
        ...productFragment
      }
    }
  }
}
