#import "./ProductFragment.gql"

query allProductsByTypeId($typeId: Int, $sort: [ProductSortEnum] = [DATE_POSTED_DESC]) {
  allProducts(filters: { typeId: $typeId }, sort: $sort) {
    edges {
      node {
        ...productFragment
      }
    }
  }
}
