fragment beam on Beam {
  id
  productId
  name
  contact
  dateProduced
  producedBy
  datePosted
  postedBy
  dateUpdated
  updatedBy
  paths {
    edges {
      node {
        id
        path
        note
      }
    }
  }
  note
  map {
    name
  }
  parentBeam {
    name
  }
  childBeams {
    edges {
      node {
        name
      }
    }
  }
}
