query Map($name: String) {
  map(name: $name) {
    mapId
    name
    datePosted
    mapper
    mapFilePaths {
      edges {
        node {
          path
          note
        }
      }
    }
    note
    beams {
      edges {
        node {
          beamId
          name
        }
      }
    }
  }
}
