fragment map on Map {
  id
  productId
  name
  contact
  dateProduced
  producedBy
  datePosted
  postedBy
  dateUpdated
  updatedBy
  paths {
    edges {
      node {
        id
        pathId
        path
        note
      }
    }
  }
  note
  beams {
    edges {
      node {
        id
        productId
        name
      }
    }
  }
}
