fragment map on Map {
  id
  mapId
  name
  contact
  dateProduced
  producedBy
  datePosted
  postedBy
  dateUpdated
  updatedBy
  mapFilePaths {
    edges {
      node {
        id
        path
        note
      }
    }
  }
  note
  beams {
    edges {
      node {
        id
        beamId
        name
      }
    }
  }
}
