fragment simulation on Simulation {
  id
  productId
  name
  contact
  dateProduced
  producedBy
  datePosted
  postedBy
  dateUpdated
  updatedBy
  paths {
    edges {
      node {
        id
        path
        note
      }
    }
  }
  note
}
